apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongodb
  namespace: tornado
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        livenessProbe:
          httpGet:
            path: /
            port: 27017
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 27017
          initialDelaySeconds: 15
          periodSeconds: 3


