kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: tornado
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: mongodb
