kind: ReplicationController
apiVersion: v1
metadata:
  name: mongodb
  namespace: tornado
spec:
  replicas: 1
  selector:
    component: mongodb
  template:
    metadata:
      labels:
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          imagePullPolicy: Never
          ports:
            - containerPort: 27017
            - containerPort: 8888 
          volumeMounts:
            - mountPath: /var/data/db
              name: nfsvol
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: nfsvol
          persistentVolumeClaim:
            claimName: mongodb-nfs

